// apps/frontend/app/auth/login/page.tsx
"use client";

import Input from "@/components/ui/Input";
import Primary from "@/components/ui/buttons/Primary";
import { login } from "@/lib/auth";

export default function Login() {
  const handleLogin = async (formData: FormData) => {
    await login(formData);
  };
  return (
    <form
      className="flex flex-col border p-4 gap-6 rounded"
      action={handleLogin}
    >
      <Input
        name="username"
        label="Username"
        type="text"
        placeholder="username"
      />
      <Input
        name="password"
        label="Password"
        type="password"
        placeholder="password"
      />
      <Primary label="Login" type="submit" />
    </form>
  );
}

// frontend/src/routes/login/+page.svelte
<script lang="ts">
  let { data, form } = $props();
</script>

<div class="p-2">
  <h1 class="flex items-center">Websocket</h1>
  <div class=" flex flex-col gap-2 w-1/3">
    <form method="POST" action="?/login">
      {#if form?.invalid}
        <p>invalid username</p>
      {/if}
      <input
        type="text"
        name="username"
        class="border p-2"
        placeholder="username"
        value={form?.username ?? ""}
      />
      <button class="bg-blue-300 p-2">Login as Guest</button>
    </form>
  </div>
</div>
