// apps/frontend/src/lib/components/ui/button/Secondary.svelte
<script lang="ts">
    type ButtonSize = "xs" | "sm" | "md";

    let {
        label,
        fn,
        size = "md",
    }: {
        label: string;
        fn: () => void;
        size: ButtonSize;
    } = $props();

    const fontSizeMap: Record<ButtonSize, string> = {
        md: "1em",
        sm: ".75em",
        xs: ".5em",
    };
</script>

<button
    style:font-size={fontSizeMap[size]}
    onclick={fn}
    class="border border-blue-500 text-blue-500 px-4 py-2 rounded"
>
    {label}
</button>

// apps/frontend/components/ui/buttons/Secondary.tsx
export default function Button({
  label,
  onClick,
  type = "button",
  disabled = false,
}: {
  label: string;
  type?: "button" | "submit" | "reset";
  onClick?: () => void;
  disabled?: boolean;
}) {
  return (
    <button
      type={type}
      onClick={onClick}
      className="bg-gray-500 hover:bg-gray-600 text-white font-semibold py-2 px-4 rounded"
      disabled={disabled}
    >
      {label}
    </button>
  );
}
