// frontend/src/routes/chat/Users.svelte
<script lang="ts">
  import { Mars } from "@lucide/svelte";
  import { Venus } from "@lucide/svelte";
  import type { User } from "../../../../shared/src";

  let { user: me, users, activeSocket, setactiveSocket, unread } = $props();

  let filterGender = $state("all");

  const filteredUsers = $derived.by<User[]>(() => {
    const allUsers = Array.from(users.values());

    switch (filterGender) {
      case "all":
        return allUsers;
      case "female":
        return allUsers.filter((usr: User) => usr.gender === "female");
      case "male":
        return allUsers.filter((usr: User) => usr.gender === "male");
      default:
        return allUsers;
    }
  });

  function handleGenderFilter(e) {
    filterGender = e.target.value;
  }
</script>

<!-- USERS -->
<div class="bg-gray-100 min-w-[300px] flex flex-col overflow-hidden">
  <div class="flex flex-col overflow-hidden flex-1">
    <div class=" bg-gray-200 py-2 px-3 shrink-0">
      <h2 class="font-bold">Users</h2>
      <form action="">
        <label>
          <input
            name="gender"
            onchange={(e) => handleGenderFilter(e)}
            type="radio"
            value="all"
          />
          All
        </label>
        <label>
          <input
            name="gender"
            onchange={(e) => handleGenderFilter(e)}
            type="radio"
            value="female"
          />
          Female
        </label>
        <label>
          <input
            name="gender"
            onchange={(e) => handleGenderFilter(e)}
            type="radio"
            value="male"
          />
          Male
        </label>
      </form>
    </div>
    <ul class="flex-1 overflow-y-auto">
      {#each filteredUsers as user (user.uid)}
        <li>
          <button
            class="px-2 py-0.5 w-full hover:bg-gray-300 relative flex gap-1 border-gray-200"
            id={user.uid}
            style={activeSocket?.uid === user.uid
              ? "background-color: gray; color: white;"
              : ""}
            onclick={(e) => setactiveSocket(user)}
          >
            {#if user.uid === me.uid}
              You
            {:else}
              {#if unread.has(user.uid!)}
                <div
                  class=" w-1.5 h-1.5 rounded-full bg-green-500 absolute left-0"
                ></div>
              {/if}
              <span class="flex items-center gap-1">
                {#if user.gender === "male"}
                  <Mars size={16} class="text-blue-500" />
                {:else if user.gender === "female"}
                  <Venus size={17} class="text-pink-500" />
                {/if}
                {user.username}
              </span>
            {/if}
          </button>
        </li>
      {/each}
    </ul>
  </div>
</div>

// apps/frontend/app/chat/chats/Users.tsx
"use client";

import { useUserStore } from "@/lib/store/userStore";
import Link from "next/link";
import { useState } from "react";

export default function Users() {
  const users = useUserStore((state) => state.users);
  const userIndex = useUserStore((state) => state.userIndex);
  const userIds = Array.from(userIndex.values());

  const [selectedId, setSelected] = useState(userIds[0]);

  return (
    <div className="flex flex-col gap-2">
      <ul className="flex flex-col gap-1 bg-gray-100 rounded-lg border border-gray-300 p-2 my-2">
        <h2 className="px-2 flex items-center gap-2">
          <span className="relative flex size-2">
            <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-green-400 opacity-75"></span>
            <span className="relative inline-flex size-2 rounded-full bg-sky-500"></span>
          </span>
          <span className="text-sm font-bold">Online</span>
        </h2>
        {userIds.map((id) => (
          <li key={id}>
            <Link
              href={`/chat/chats/${id}?type=user&name=${users[id]?.username}`}
              className={`block px-3 py-1 rounded  
                  ${selectedId === id && "bg-blue-100 text-blue-600  border-blue-300"} hover:bg-blue-100 `}
              onClick={() => setSelected(id)}
            >
              {users[id]?.username}
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
}
