// apps/frontend/app/auth/register/page.tsx
"use client";

import Input from "@/components/ui/Input";
import RadioGroup from "@/components/ui/RadioGroup";

import Primary from "@/components/ui/buttons/Primary";

import countries from "@/lib/countries.json";
import Select from "@/components/ui/Select";
import { useState } from "react";

export default function Register() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [gender, setGender] = useState("");
  const [age, setAge] = useState(18);
  const [country, setCountry] = useState({ key: "us", name: "United States" });

  return (
    <form className="flex flex-col border p-4 gap-6 rounded">
      <Input
        label="Username"
        type="text"
        placeholder="username"
        value={username}
        onChange={(e) => setUsername(e.target.value)}
      />

      <Input
        label="Password"
        type="password"
        placeholder="password"
        value={password}
        onChange={(e) => setPassword(e.target.value)}
      />

      <Input
        label="Confirm Password"
        type="password"
        placeholder="confirm password"
        value={confirmPassword}
        onChange={(e) => setConfirmPassword(e.target.value)}
      />

      <RadioGroup
        label="Gender"
        value={gender}
        onChange={(value) => setGender(value)}
        options={[
          { id: "male", name: "Male", value: "male" },
          { id: "female", name: "Female", value: "female" },
          { id: "other", name: "Other", value: "other" },
        ]}
      />

      <Input
        type="number"
        label="Age"
        placeholder="Age"
        min="18"
        value={age}
        onChange={(e) => setAge(Number(e.target.value))}
      />

      <Select
        label="Country"
        options={countries}
        value={country}
        onChange={(value) => setCountry(value)}
      />

      <Primary label="Register" onClick={() => {}} />
    </form>
  );
}

// apps/frontend/src/routes/auth/register/+page.svelte
<script lang="ts">
    import { enhance } from "$app/forms";
    import Primary from "$lib/components/ui/button/Primary.svelte";
    import Input from "$lib/components/ui/form/Input.svelte";
    import RadioGroup from "$lib/components/ui/form/RadioGroup.svelte";
    import Select from "$lib/components/ui/form/Select.svelte";
    import countries from "$lib/countires.json";
    import { chatStore } from "$lib/store/store.svelte.js";
    import { debounce } from "$lib/utils/debounce";
    import {
        CircleAlert,
        CircleCheck,
        User as UserIcon,
        EyeOff,
        Eye,
    } from "@lucide/svelte";
    import { type User } from "@pingxy/shared";
    import { onMount } from "svelte";

    let { form } = $props();

    onMount(() => {});
    const range = (start: number, end: number) =>
        Array.from({ length: end - start + 1 }, (_, i) => i + start);

    const ageOptions = range(18, 70).map((age) => ({
        name: age,
        value: age,
    }));
    const genderOptions = [
        { id: 1, name: "gender", label: "Male", value: "male" },
        { id: 2, name: "gender", label: "Female", value: "female" },
        { id: 3, name: "gender", label: "Other", value: "other" },
    ];
    let username = $state("");
    let password = $state("");
    let confirmPassword = $state("");
    let gender = $state("all");
    let age = $state(18);
    let country = $state("AF");

    let errText = $state("");
    let okText = $state("");

    let loading = $state(false); // let geoLocation = $state();

    const debounceCheck = debounce(async () => {
        // use Constant from shared/constants.ts for length cheking..
        if (!username) {
            errText = "username is required";
            return;
        } else if (username.length < 3) {
            errText = "Username too short, min 3 characters";
            return;
        } else if (username.length > 20) {
            errText = "Username too long, max 20 characters";
            return;
        } else if (!/^[a-zA-Z][a-zA-Z0-9]*$/.test(username)) {
            errText = "Inavalid character in username";

            return;
        }

        const response = await fetch(`/api/users/check?username=${username}`, {
            method: "GET",
        });

        const data = await response.json();

        if (data.available) {
            errText = "";
            okText = "Ok";
        } else {
            errText = "Username Taken";
        }
    }, 500);
</script>

<form
    class="flex flex-col gap-4 text-sm"
    method="POST"
    use:enhance={() => {
        loading = true;
        return async ({ result, update }) => {
            if (result.type === "success" && result.data !== undefined) {
                chatStore.currentUser = result.data.user as User;
            }

            await update();
            loading = false;
        };
    }}
>
    <Input
        label="Username"
        name="username"
        icon={UserIcon}
        placeholder="Enter your username"
        bind:value={username}
        oninput={() => debounceCheck()}
        autocomplete="username"
        {errText}
        {okText}
    />
    <Input
        label="Password"
        type="password"
        name="password"
        autocomplete="new-password"
        icon={EyeOff}
        toggleIcon={Eye}
        placeholder="Enter your password"
        bind:value={password}
    />
    <Input
        label="Confirm Password"
        type="password"
        name="confirmPassword"
        autocomplete="new-password"
        icon={EyeOff}
        toggleIcon={Eye}
        placeholder="Confirm your password"
        bind:value={confirmPassword}
    />
    <RadioGroup label="Gender" options={genderOptions} />

    <Select label="Age" name="age" bind:value={age} options={ageOptions} />
    <Select
        label="Country"
        name="country"
        bind:value={country}
        options={countries}
    />

    <Primary size="md" label="Register" {loading} fn={() => {}} />
</form>
